package esprit.tn.education.entities;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "audio_sessions")
public class AudioSession {

    @Id
    private String id;

    private String activityId;
    private String patientId;

    /**
     * Session lifecycle: INIT → IN_PROGRESS → COMPLETED | STOPPED
     */
    @Builder.Default
    private String sessionStatus = "INIT";

    /** Short sentences summarising the video, generated by Mock LLM */
    @Builder.Default
    private List<String> summary = new ArrayList<>();

    /** Questions generated by Mock LLM */
    @Builder.Default
    private List<AudioQuestion> questions = new ArrayList<>();

    @Builder.Default
    private int currentQuestionIndex = 0;

    private int totalQuestions;

    @Builder.Default
    private int correctAnswers = 0;

    @Builder.Default
    private int partialAnswers = 0;

    @Builder.Default
    private int incorrectAnswers = 0;

    @Builder.Default
    private int silenceCount = 0;

    /** Closing sentences spoken at the end of the session */
    @Builder.Default
    private String finalSummary = "";

    /** Patient's chosen language: "fr" (default) or "en" */
    @Builder.Default
    private String language = "fr";

    /** Full transcript of AI ↔ Patient exchanges */
    @Builder.Default
    private List<AudioExchange> transcriptHistory = new ArrayList<>();

    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();

    @Builder.Default
    private LocalDateTime updatedAt = LocalDateTime.now();
}
