package tn.esprit.smartwatchservice.service;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import tn.esprit.smartwatchservice.dto.HeartRateRequest;
import tn.esprit.smartwatchservice.entity.HeartRateRecord;
import tn.esprit.smartwatchservice.repository.HeartRateRepository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * Original heart-rate service — kept for backward compatibility.
 *
 * @deprecated Use {@link HeartRateIngestionService} for ingestion (via Kafka)
 *             and {@link HeartRateQueryService} for queries.
 */
@Service
@RequiredArgsConstructor
public class HeartRateService {

    private final HeartRateRepository heartRateRepository;

    /**
     * Save a new heart-rate record from a request DTO.
     * The recordedAt timestamp is always generated by the server.
     *
     * @deprecated Use the new async Kafka-based ingestion flow:
     *             POST /api/heart-rate/ingest → HeartRateIngestionService
     */
    @Deprecated
    public HeartRateRecord save(HeartRateRequest request) {
        HeartRateRecord record = HeartRateRecord.builder()
                .userId(request.getUserId())
                .deviceName(request.getDeviceName())
                .bpm(request.getBpm())
                .recordedAt(LocalDateTime.now())
                .build();
        return heartRateRepository.save(record);
    }

    /**
     * Get the most recent heart-rate record for a user.
     * @deprecated Use {@link HeartRateQueryService#getLatest(Long)}
     */
    @Deprecated
    public Optional<HeartRateRecord> getLatest(Long userId) {
        return heartRateRepository.findTopByUserIdOrderByRecordedAtDesc(userId);
    }

    /**
     * Get the full heart-rate history for a user (most recent first).
     * @deprecated Use {@link HeartRateQueryService#getHistory(Long)}
     */
    @Deprecated
    public List<HeartRateRecord> getHistory(Long userId) {
        return heartRateRepository.findByUserIdOrderByRecordedAtDesc(userId);
    }

    /**
     * Get a specific record by its MongoDB ID.
     * @deprecated Use {@link HeartRateQueryService#getById(String)}
     */
    @Deprecated
    public Optional<HeartRateRecord> getById(String id) {
        return heartRateRepository.findById(id);
    }

    /**
     * Delete a specific record by its MongoDB ID.
     * @deprecated Use {@link HeartRateQueryService#delete(String)}
     */
    @Deprecated
    public void delete(String id) {
        heartRateRepository.deleteById(id);
    }
}
