spring.application.name=patient-medecin-service
server.port=8089
server.forward-headers-strategy=framework

# MongoDB
spring.data.mongodb.uri=mongodb+srv://yosr:yosr@cluster0.a5ojkea.mongodb.net/patient_medecin_db?appName=Cluster0
spring.data.mongodb.auto-index-creation=true

spring.main.allow-bean-definition-overriding=true

# Multipart Upload Limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Gmail SMTP (RappelEmailService)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mkadi.8706@gmail.com
spring.mail.password=kgfsomzfmxwkjhbt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Eureka registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Jackson: serialize LocalDate/LocalTime as strings
spring.jackson.serialization.write-dates-as-timestamps=false
