spring.application.name=patient-medecin-service
server.port=8089
server.forward-headers-strategy=framework

# MongoDB local
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=patient_medecin_db
spring.data.mongodb.auto-index-creation=true

spring.main.allow-bean-definition-overriding=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mkadi.8706@gmail.com
spring.mail.password=kgfsomzfmxwkjhbt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
spring.jackson.serialization.write-dates-as-timestamps=false