spring.application.name=geo-service
server.port=8085
server.forward-headers-strategy=framework

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/geo_db
spring.data.mongodb.auto-index-creation=true

spring.main.allow-bean-definition-overriding=true

# Multipart Upload Limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Eureka registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=votre@gmail.com
spring.mail.password=votre_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# application.properties geo-service
infobip.api-key=3f21e2010eedf1c52baa593bc52d4e73-1e80e6be-8daa-4100-893e-17c33d3da07b
infobip.base-url=https://l229yj.api.infobip.com
infobip.from=AlzCare
backpi.url=http://localhost:8082
alzcare.ai.location-url=http://localhost:8000/predict-location
alzcare.ai.hospital-url=http://localhost:8000/predict-hospital
