spring.application.name=smartwatch-service
server.port=8095
server.forward-headers-strategy=framework

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/smartwatch_db
spring.data.mongodb.auto-index-creation=true

spring.main.allow-bean-definition-overriding=true

# Eureka registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
