spring.application.name=donation-service
server.port=8087
server.forward-headers-strategy=framework

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/donation_db
spring.data.mongodb.auto-index-creation=true

spring.main.allow-bean-definition-overriding=true

# Eureka registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Stripe Configuration
# Default key for test environment. You should override this with environment variable.
stripe.api.key=${STRIPE_API_KEY:sk_test_51TJC86LeZbu5wDY4qoJM4IpEFPYIVCgpDPsIVBGxASan8zYyLV0FwUvjvqZ8flcAfnGAvIUw2g8LueiZPN5FIkOg00oSilhhut}

# Frontend URL
frontend.url=${FRONTEND_URL:http://localhost:4200}

