spring.application.name=collab-service
server.port=8081
server.forward-headers-strategy=framework

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/collab_db
spring.data.mongodb.auto-index-creation=true

spring.main.allow-bean-definition-overriding=true

# Multipart Upload Limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Hugging Face (Sentiment Analysis)
huggingface.api.url=https://router.huggingface.co/models/cardiffnlp/twitter-roberta-base-sentiment-latest
huggingface.api.token=${HF_TOKEN:}

# OpenRouter (AI)
openrouter.api.key=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
openrouter.api.url=https://openrouter.ai/api/v1/chat/completions
openrouter.model=openrouter/free

# Google Gemini AI
spring.ai.google.gemini.model-id=gemini-1.5-flash
spring.ai.google.gemini.api-key=${GEMINI_KEY:}

# Eureka registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
